[package]
name = "aoc2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_cmd = "2"
bit_field = "0.10"
glam = "0.20"
itertools = "0.10"
parse-display = "0.5"

[profile.release]
debug = true